### ISSUE TITLE
As a developer I want to know which JS Frameworks should be included

### ISSUE THREAD

**Issue by james02135** [james02135/Tooling-Project#3]
AC:
research into different frameworks; React, Node, Angular, Vue, etc.

DOD:
enough knowledge about the various frameworks to make a decision on which to be included initially

**Comment by StephenCoady** [comment]
This one confuses me a little, react is a front end framework, snyk is a container vulnerability tool and NPM is a package manager for node module dependencies. If you want to bootstrap a project with react for developers then there are tools that do that already, you could probably incorporate those as direct dependencies of your project.

Or do you mean decide on the actual stack of your project? Maybe that is what it is and the word "included" made me think of the other issues where you talk about things being included in the project.

**Comment by james02135** [comment]
was confused myself...corrected my mistake there.

When I say "include", what I mean is to be a part of the overall project as an available option to the user.

**Comment by StephenCoady** [comment]
OK then I'm more confused now :joy: 

Maybe take a look at something like: https://www.freecodecamp.org/news/how-and-why-to-write-great-user-stories-f5a110668246/
