### ISSUE TITLE
As a developer I would like a CI environment to build my project

### ISSUE THREAD

**Issue by james02135** [james02135/Tooling-Project#4]
AC:
- research into CI build frameworks, Jenkins, CircleCI, Travis

DOD:
- have selected 3 to be included in the project

**Comment by StephenCoady** [comment]
What does "included" mean here? 

To me a flow here might be:

* Generate the corresponding `Jenkinsfile` `travis.yml` etc.
* Possibly hook into one of the cloud providers automatically (this may be complicated, the service will need to be given permission via Github/Gitlab first)
* Configure the service based on some questions you have asked
