### ISSUE TITLE
As a developer I would like tools to help ID code smells, duplicates, security issues, etc.

### ISSUE THREAD

**Issue by james02135** [james02135/Tooling-Project#5]
AC:
- ID static code tools like Sonarqube, Bandit, LGTM

DOD:
- have ID'd min 3 to include in the project

**Comment by StephenCoady** [comment]
What does "include" mean here? Where will these tools run? 2 of the 3 you mentioned are cloud services and to my knowledge need a service to be running either locally or in the cloud.
