### ISSUE TITLE
As a developer I would like to be able to use Docker to containerize my project

### ISSUE THREAD

**Issue by james02135** [james02135/Tooling-Project#6]
AC:
- figure out how to incorporate Docker into the pipeline

DOD:
- Docker is working

**Comment by StephenCoady** [comment]
OK so maybe this one falls into the previous "install" one. Are you going to install everything in Docker containers by the end or is this a vehicle you are making available? 

When you say incorporate, how granular are you going? Do you mean they can provide you with a Docker image and you will run it or do you mean you will build an image from their code? The second option could be very large but would be cool. In my opinion it might be easier to:

1. Ask at run time if they would like to use Docker.
2. Generate a Dockerfile in the repo if they do, or they can provide a pre-made Docker Image.
3. Tell them they need to fill out this Dockerfile with the specifics of their application
4. Once filled out, you can build the image and push it where it needs to be.
