### ISSUE TITLE
As a developer I want the option to install the project on my local machine or AWS

### ISSUE THREAD

**Issue by james02135** [james02135/Tooling-Project#7]
AC:
- have the option to install locally or AWS
- If choice is AWS, begin initializing a new instance

DOD:
- both choices work properly

**Comment by StephenCoady** [comment]
I think this is quite broad, and as a developer starting work on this I would have a lot of questions. Just some from the top of my head:

* What does "install" mean? 
* What dependency mesh are we assuming? If we are assuming none, then how do we make sure dependencies are present. If we are assuming all dependencies are present then the value of the "install" decreases IMO.
* There will be some meta data attached to the install (once that is defined) such as networking, directories, the user to run as, the entrypoint into the application etc. This will need to be catered for as part of this issue.
